[package]
name = "rust-persist"
version = "0.5.0"
authors = ["Dennis Schwerdel <schwerdel@googlemail.com>"]
description = "Persistent storage for Rust"
edition = "2018"

[dev-dependencies]

[dependencies]
mmap = "^0.1"
safemem = "^0.3.3"

[features]
default = []
bench = []
